# Generated by Django 2.2.5 on 2020-05-14 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('img', models.ImageField(default='default/news-no-img.jpg', upload_to='news')),
            ],
        ),
    ]
