# Generated by Django 3.0.6 on 2020-05-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='Анонимус', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(default='default/news-no-img.jpg', null=True, upload_to='news'),
        ),
    ]
